name: als832
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib=3.4.2
  - astra-toolbox::astra-toolbox
  - conda-forge::tomopy
  - conda-forge::dxchange
  - conda-forge::svmbir
  - conda-forge::scikit-image
  - conda-forge::jupyterlab=3.4.4
  - conda-forge::ipympl=0.86
  - conda-forge::ipyfilechooser=0.6.0
  - conda-forge::olefile
  - conda-forge::astropy